/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CrearUsuarioDto } from '../../models/crear-usuario-dto';
import { CrearUsuarioDtoApiResponse } from '../../models/crear-usuario-dto-api-response';

export interface ActualizarUsuario$Plain$Params {
      body?: CrearUsuarioDto
}

export function actualizarUsuario$Plain(http: HttpClient, rootUrl: string, params?: ActualizarUsuario$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CrearUsuarioDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, actualizarUsuario$Plain.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CrearUsuarioDtoApiResponse>;
    })
  );
}

actualizarUsuario$Plain.PATH = '/api/Usuarios/ActualizarUsuario';
