/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CrearUsuarioDtoApiResponse } from '../../models/crear-usuario-dto-api-response';

export interface EliminarCliente$Json$Params {
  id?: string;
}

export function eliminarCliente$Json(http: HttpClient, rootUrl: string, params?: EliminarCliente$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CrearUsuarioDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, eliminarCliente$Json.PATH, 'delete');
  if (params) {
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CrearUsuarioDtoApiResponse>;
    })
  );
}

eliminarCliente$Json.PATH = '/api/Usuarios/EliminarCliente';
