/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListaUsuarioPlantaListApiResponse } from '../../models/lista-usuario-planta-list-api-response';

export interface GetAllUsers$Json$Params {
}

export function getAllUsers$Json(http: HttpClient, rootUrl: string, params?: GetAllUsers$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ListaUsuarioPlantaListApiResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllUsers$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListaUsuarioPlantaListApiResponse>;
    })
  );
}

getAllUsers$Json.PATH = '/api/Usuarios/GetAllUsers';
