/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetUsuarioDtoListApiResponse } from '../../models/get-usuario-dto-list-api-response';

export interface GetUserById$Json$Params {
  usuarioID?: string;
}

export function getUserById$Json(http: HttpClient, rootUrl: string, params?: GetUserById$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<GetUsuarioDtoListApiResponse>> {
  const rb = new RequestBuilder(rootUrl, getUserById$Json.PATH, 'get');
  if (params) {
    rb.query('usuarioID', params.usuarioID, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetUsuarioDtoListApiResponse>;
    })
  );
}

getUserById$Json.PATH = '/api/Usuarios/GetUserByID';
