/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsuarioDtoListApiResponse } from '../../models/usuario-dto-list-api-response';

export interface GetUserByEmail$Plain$Params {
  correo?: string;
}

export function getUserByEmail$Plain(http: HttpClient, rootUrl: string, params?: GetUserByEmail$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioDtoListApiResponse>> {
  const rb = new RequestBuilder(rootUrl, getUserByEmail$Plain.PATH, 'get');
  if (params) {
    rb.query('correo', params.correo, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioDtoListApiResponse>;
    })
  );
}

getUserByEmail$Plain.PATH = '/api/Usuarios/GetUserByEmail';
