/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CrearUsuarioPlantaDto } from '../../models/crear-usuario-planta-dto';

export interface GuardaRelacionUsuarioPlanta$Plain$Params {
      body?: Array<CrearUsuarioPlantaDto>
}

export function guardaRelacionUsuarioPlanta$Plain(http: HttpClient, rootUrl: string, params?: GuardaRelacionUsuarioPlanta$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
  const rb = new RequestBuilder(rootUrl, guardaRelacionUsuarioPlanta$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: String((r as HttpResponse<any>).body) === 'true' }) as StrictHttpResponse<boolean>;
    })
  );
}

guardaRelacionUsuarioPlanta$Plain.PATH = '/api/Usuarios/GuardaRelacionUsuarioPlanta';
