/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Perfile } from '../models/perfile';
export interface Accione {
  codAccion?: string | null;
  descripcion?: string | null;
  perfils?: Array<Perfile> | null;
  seccion?: string | null;
}
