/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PerfilAccion } from '../models/perfil-accion';
export interface Accione {
  codAccion?: string | null;
  descripcion?: string | null;
  perfilAccions?: Array<PerfilAccion> | null;
  seccion?: string | null;
}
