/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CTipoEvento } from '../models/c-tipo-evento';
import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
export interface Bitacora {
  descripcionEvento?: string | null;
  empresa?: Empresa;
  empresaId?: string | null;
  fechaYhoraEvento?: string | null;
  identificacionEvento?: string | null;
  numeroRegistro?: number;
  planta?: Plantum;
  plantaId?: string | null;
  tipoEvento?: string | null;
  tipoEventoNavigation?: CTipoEvento;
  usuarioResponsable?: string | null;
}
