/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Documento } from '../models/documento';
import { Plantum } from '../models/plantum';
export interface CCaracter {
  descripcion?: string | null;
  documentos?: Array<Documento> | null;
  id?: number;
  planta?: Array<Plantum> | null;
  tipoCaracter?: string | null;
}
