/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Dictamene } from '../models/dictamene';
import { DocumentoProducto } from '../models/documento-producto';
export interface CClaveProducto {
  claveProducto?: string | null;
  descripcion?: string | null;
  dictamenes?: Array<Dictamene> | null;
  documentoProductos?: Array<DocumentoProducto> | null;
  id?: number;
}
