/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentoProducto } from '../models/documento-producto';
export interface CClaveSubproducto {
  claveSubProducto?: string | null;
  descripcion?: string | null;
  documentoProductos?: Array<DocumentoProducto> | null;
  id?: number;
}
