/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Tanque } from '../models/tanque';
export interface CEstadoTanque {
  descripcion?: string | null;
  estadoTanque?: string | null;
  tanques?: Array<Tanque> | null;
}
