/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Bitacora } from '../models/bitacora';
import { DocumentoBitacora } from '../models/documento-bitacora';
export interface CTipoEvento {
  bitacoras?: Array<Bitacora> | null;
  descripcion?: string | null;
  documentoBitacoras?: Array<DocumentoBitacora> | null;
  id?: number | null;
  tipoEvento?: string | null;
}
