/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmpresaImpExp } from '../models/empresa-imp-exp';
import { TipoDocumento } from '../models/tipo-documento';
export interface CTipoImpExp {
  descripcion?: string | null;
  empresaImpExps?: Array<EmpresaImpExp> | null;
  tipoDocumento?: string | null;
  tipoDocumentoNavigation?: TipoDocumento;
  tipoImportacion?: string | null;
}
