/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmpresaImpExp } from '../models/empresa-imp-exp';
export interface CTipo {
  descripcion?: string | null;
  empresaImpExps?: Array<EmpresaImpExp> | null;
  tipo?: string | null;
}
