/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
export interface CertificadosProveedore {
  activo?: boolean;
  adjuntoPdfcertificado?: string | null;
  adjuntoXmlcertificado?: string | null;
  empresa?: Empresa;
  empresaId?: string | null;
  fechaEmisionCertificado?: string;
  numeroFolioCertificado?: string | null;
  resultadoCertificado?: string | null;
  rfcCertificado?: string | null;
}
