/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
export interface CompAlmCfdinacionalDocumento {
  claveTanque?: string | null;
  consecutivo?: number;
  empresa?: Empresa;
  empresaId?: string | null;
  noDocumento?: string | null;
  pdf?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  xml?: string | null;
}
