/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
export interface CompAlmDictaman {
  empresa?: Empresa;
  empresaId?: string | null;
  fechaEmisionDictamen?: string | null;
  loteDictamen?: string | null;
  noDocumento?: string | null;
  numeroFolioDictamen?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  resultadoDictamen?: string | null;
  rfcDictamen?: string | null;
}
