/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
import { TClaveUnidadMedidum } from '../models/t-clave-unidad-medidum';
export interface CompAlmCfdinacional {
  aclaracion?: string | null;
  cargoPorCapacidadAlmac?: number | null;
  cargoPorUsoAlmac?: number | null;
  cargoVolumetricoAlmac?: number | null;
  claveTanque?: string | null;
  consecutivo?: number;
  consecutivoRecepcion?: number | null;
  contraprestacion?: number | null;
  descuento?: number | null;
  empresa?: Empresa;
  empresaId?: string | null;
  fechaYhoraTransaccion?: string | null;
  noDocumento?: string | null;
  nombreClienteOproveedor?: string | null;
  permisoProveedor?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  poderCalorifico?: number | null;
  precioCompra?: number | null;
  precioUnitario?: number | null;
  proveedorId?: string | null;
  rfcClienteOproveedor?: string | null;
  tarifaDeAlmacenamiento?: number | null;
  tipoCfdi?: string | null;
  tipoDocumento?: string | null;
  tipoEs?: string | null;
  um?: number | null;
  umNavigation?: TClaveUnidadMedidum;
  uuid?: string | null;
  valorNumerico?: number | null;
}
