/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Documento } from '../models/documento';
import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
export interface CompAlmProveedorNacionalMensual {
  documento?: Documento;
  empresa?: Empresa;
  empresaId?: string | null;
  noDocumento?: string | null;
  nombreClienteOproveedor?: string | null;
  permisoProveedor?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  proveedorId?: string | null;
  rfcClienteOproveedor?: string | null;
}
