/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
export interface CompAlmCertificado {
  empresa?: Empresa;
  empresaId?: string | null;
  fechaEmisionCertificado?: string | null;
  noDocumento?: string | null;
  numeroFolioCertificado?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  resultadoCertificado?: string | null;
  rfcCertificado?: string | null;
}
