/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CrearUsuarioPlantaDto {
  plantaDescripcion?: string | null;
  plantaId?: string | null;
  usuarioId?: string | null;
}
