/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CrearEmpresaDto {
  activa?: boolean;
  empresaId?: string | null;
  fechaCreacion?: string;
  razonSocial?: string | null;
  rfc?: string | null;
  rfcRepresentanteLegal?: string | null;
  versionCtrVol?: string | null;
}
