/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CrearPerfilDto {
  acciones?: string | null;
  descripcion?: string | null;
  perfil?: string | null;
  perfilId?: number;
}
