/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CrearEmpresaPlantaDto {
  empresaId?: string | null;
  id?: string | null;
  plantaId?: string | null;
}
