/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CrearPerfilEmpresaDto {
  empresaId?: string | null;
  perfilId?: number;
  plantaId?: string | null;
}
