/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CrearEmpresaDto } from '../models/crear-empresa-dto';
export interface CrearEmpresaDtoApiResponse {
  message?: string | null;
  result?: CrearEmpresaDto;
  success?: boolean;
}
