/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CrearPerfilAccionDto {
  codAccion?: string | null;
  id?: string | null;
  perfilId?: number;
}
