/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CrearEmpresaProveedorDto {
  disponibilidad?: boolean;
  empresaId?: string | null;
  proveedorId?: string | null;
}
