/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CrearUsuarioPlantaDto } from '../models/crear-usuario-planta-dto';
export interface CrearUsuarioPlantaDtoListApiResponse {
  message?: string | null;
  result?: Array<CrearUsuarioPlantaDto> | null;
  success?: boolean;
}
