/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CrearPerfilDto } from '../models/crear-perfil-dto';
export interface CrearPerfilDtoApiResponse {
  message?: string | null;
  result?: CrearPerfilDto;
  success?: boolean;
}
