/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CrearUsuarioDto {
  activo?: boolean;
  correo?: string | null;
  nombre?: string | null;
  password?: string | null;
  perfilId?: number;
  usuarioId?: string | null;
}
