/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CrearUsuarioDto } from '../models/crear-usuario-dto';
export interface CrearUsuarioDtoApiResponse {
  message?: string | null;
  result?: CrearUsuarioDto;
  success?: boolean;
}
