/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CClaveProducto } from '../models/c-clave-producto';
import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
export interface Dictamene {
  activo?: boolean;
  adjuntoPdfdictamen?: string | null;
  adjuntoXmldcitamen?: string | null;
  empresa?: Empresa;
  empresaId?: string | null;
  fechaEmisionDictamen?: string;
  idClaveProducto?: number;
  idClaveProductoNavigation?: CClaveProducto;
  loteDictamen?: string | null;
  numeroFolioDictamen?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  resultadoDictamen?: string | null;
  rfcDictamen?: string | null;
  rfcPersonal?: string | null;
  rfcRepresentanteLegalProveedor?: string | null;
}
