/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Plantum } from '../models/plantum';
export interface DispensariosManguera {
  claveDispensario?: string | null;
  consecutivo?: number;
  identificadorManguera?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
}
