/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CClaveProducto } from '../models/c-clave-producto';
import { CClaveSubproducto } from '../models/c-clave-subproducto';
import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
import { Producto } from '../models/producto';
import { TClaveUnidadMedidum } from '../models/t-clave-unidad-medidum';
export interface DocumentoProducto {
  claveProducto?: number | null;
  claveProductoNavigation?: CClaveProducto;
  claveSubProducto?: number | null;
  claveSubProductoNavigation?: CClaveSubproducto;
  concentracionSustanciaMarcaje?: string | null;
  empresa?: Empresa;
  empresaId?: string | null;
  marcaComercial?: string | null;
  marcaje?: string | null;
  noDocumento?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  producto?: Producto;
  productoId?: string | null;
  um?: number | null;
  umNavigation?: TClaveUnidadMedidum;
}
