/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
export interface DocumentoDiarioMedicionDispensario {
  claveDispensario?: string | null;
  consecutivo?: number;
  empresa?: Empresa;
  empresaId?: string | null;
  incertidumbreMedicionSistMedicionDispensario?: number | null;
  localizOdescripSistMedicionDispensario?: string | null;
  noDocumento?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  sistemaMedicionDispensario?: string | null;
  vigenciaCalibracionSistMedicionDispensario?: string | null;
}
