/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
export interface DocumentoGenerado {
  consecutivo?: number;
  descripcion?: string | null;
  empresa?: Empresa;
  empresaId?: string | null;
  fechaGeneracion?: string;
  guid?: string | null;
  noDocumento?: string | null;
  nombre?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  xml?: string | null;
}
