/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
export interface DocumentoExistencium {
  empresa?: Empresa;
  empresaId?: string | null;
  fechaActual?: string;
  fechaYhoraEstaMedicionMes?: string;
  noDocumento?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  valorNumerico?: number;
}
