/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CCaracter } from '../models/c-caracter';
import { CompAlmProveedorNacionalMensual } from '../models/comp-alm-proveedor-nacional-mensual';
import { DocumentoEstatus } from '../models/documento-estatus';
import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
import { TClavePermiso } from '../models/t-clave-permiso';
import { TipoDocumento } from '../models/tipo-documento';
import { VersionControlVolumetrico } from '../models/version-control-volumetrico';
export interface Documento {
  claveInstalacion?: string | null;
  compAlmProveedorNacionalMensual?: CompAlmProveedorNacionalMensual;
  descripcionInstalacion?: string | null;
  empresa?: Empresa;
  empresaId?: string | null;
  estatus?: string | null;
  estatusNavigation?: DocumentoEstatus;
  fechaGeneracion?: string | null;
  fechayHoraCorteDiario?: string | null;
  fechayHoraReporteMes?: string | null;
  identificadorUnico?: string | null;
  instalacionAlmacenGasNatural?: string | null;
  modalidadPermiso?: number | null;
  modalidadPermisoNavigation?: TClavePermiso;
  noDocumento?: string | null;
  nombreImportacion?: string | null;
  numContratoOasignacion?: string | null;
  numPermiso?: string | null;
  numeroDispensarios?: number | null;
  numeroDuctosEntradaSalida?: number | null;
  numeroDuctosTransporteDistribucion?: number | null;
  numeroPozos?: number | null;
  numeroTanques?: number | null;
  periodo?: number | null;
  planta?: Plantum;
  plantaId?: string | null;
  porcentajeCaptura?: string | null;
  rfcProveedorInformatico?: string | null;
  tipoCaracter?: number | null;
  tipoCaracterNavigation?: CCaracter;
  tipoDocumento?: string | null;
  tipoDocumentoNavigation?: TipoDocumento;
  versionCtrVol?: string | null;
  versionCtrVolNavigation?: VersionControlVolumetrico;
}
