/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
export interface DocumentoMedicionTanque {
  claveIdentificacionTanque?: string | null;
  consecutivo?: number;
  empresa?: Empresa;
  empresaId?: string | null;
  incertidumbreMedicionSistMedicionTanque?: number | null;
  localizOdescripSistMedicionTanque?: string | null;
  noDocumento?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  sistemaMedicionTanque?: string | null;
  vigenciaCalibracionSistMedicionTanque?: string | null;
}
