/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
export interface DocumentoDiarioDispenEntrega {
  claveIdentificacionTanque?: string | null;
  claveIdentificadorDispensario?: string | null;
  consecutivo?: number;
  empresa?: Empresa;
  empresaId?: string | null;
  fechaYhoraEntrega?: string | null;
  identificadorManguera?: string | null;
  noDocumento?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  precioVentaTotalizadorInsta?: number | null;
  tipoDeRegistro?: string | null;
  volEntregadoTotalAcumValorNumerico?: number | null;
  volEntregadoTotalInstaValorNumerico?: number | null;
}
