/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Documento } from '../models/documento';
export interface DocumentoEstatus {
  descripcion?: string | null;
  documentos?: Array<Documento> | null;
  estatus?: string | null;
}
