/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
import { TClaveUnidadMedidum } from '../models/t-clave-unidad-medidum';
export interface DocumentoTanque {
  capFondajeValorNumerico?: number | null;
  capGasTalonValorNumerico?: number | null;
  capOperativaValorNumerico?: number | null;
  capTotalValorNumerico?: number | null;
  capUtilValorNumerico?: number | null;
  claveIdentificacionTanque?: string | null;
  empresa?: Empresa;
  empresaId?: string | null;
  estadoTanque?: string | null;
  localizacionYodescripcionTanque?: string | null;
  noDocumento?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  um?: number | null;
  umNavigation?: TClaveUnidadMedidum;
  vigenciaCalibracionTanque?: string | null;
  volMinOperaValorNumerico?: number | null;
}
