/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
export interface DocumentoTanqueExistencium {
  claveIdentificacionTanque?: string | null;
  empresa?: Empresa;
  empresaId?: string | null;
  fechayHoraEstaMedicion?: string | null;
  fechayHoraMedicionAnterior?: string | null;
  horaEntregaAcumulado?: string | null;
  horaRecepcionAcumulado?: string | null;
  noDocumento?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  um?: string | null;
  volumenAcumOpsRecepcion?: number | null;
  volumenExistencias?: number | null;
  volumenExistenciasAnterior?: number | null;
  volumenvolumenAcumOpsEntrega?: number | null;
}
