/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmpresaPlantaDto } from '../models/empresa-planta-dto';
export interface EmpresaPlantaDtoListApiResponse {
  message?: string | null;
  result?: Array<EmpresaPlantaDto> | null;
  success?: boolean;
}
