/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Proveedore } from '../models/proveedore';
export interface EmpresaProveedor {
  disponibilidad?: boolean;
  empresa?: Empresa;
  empresaId?: string | null;
  proveedor?: Proveedore;
  proveedorId?: string | null;
}
