/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmpresaProveedorDto } from '../models/empresa-proveedor-dto';
export interface EmpresaProveedorDtoListApiResponse {
  message?: string | null;
  result?: Array<EmpresaProveedorDto> | null;
  success?: boolean;
}
