/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmpresaPlantaDto {
  empresaId?: string | null;
  nombrePlanta?: string | null;
  plantaId?: string | null;
  razonSocial?: string | null;
}
