/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmpresaProveedorDto {
  empresaId?: string | null;
  nombreProveedor?: string | null;
  proveedorId?: string | null;
  razonSocial?: string | null;
}
