/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Plantum } from '../models/plantum';
import { Producto } from '../models/producto';
export interface EmpresaProducto {
  disponibilidad?: boolean;
  planta?: Plantum;
  plantaId?: string | null;
  producto?: Producto;
  productoId?: string | null;
}
