/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
export interface EmpresaPlantum {
  empresa?: Empresa;
  empresaId?: string | null;
  id?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
}
