/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CTipo } from '../models/c-tipo';
import { CTipoImpExp } from '../models/c-tipo-imp-exp';
import { Empresa } from '../models/empresa';
export interface EmpresaImpExp {
  activo?: boolean;
  empresa?: Empresa;
  empresaId?: string | null;
  ruta?: string | null;
  tipo?: string | null;
  tipoDocumento?: string | null;
  tipoDocumentoNavigation?: CTipoImpExp;
  tipoLayout?: string | null;
  tipoNavigation?: CTipo;
}
