/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
import { TClaveUnidadMedidum } from '../models/t-clave-unidad-medidum';
export interface EntregasMensuale {
  empresa?: Empresa;
  empresaId?: string | null;
  importeTotalEntregasMensual?: number;
  noDocumento?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  poderCalorifico?: number | null;
  poderCalorificoUm?: number | null;
  sumaVolEntregadoMesUm?: number;
  sumaVolEntregadoMesUmNavigation?: TClaveUnidadMedidum;
  sumaVolEntregadoMesValorNumerico?: number;
  totalDocumentosMes?: number;
  totalEntregasMes?: number;
}
