/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Producto } from '../models/producto';
export interface GasLp {
  composDeButanoEnGasLp?: number | null;
  composDePropanoEnGasLp?: number | null;
  producto?: Producto;
  productoId?: string | null;
}
