/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GetUsuarioDto } from '../models/get-usuario-dto';
export interface GetUsuarioDtoListApiResponse {
  message?: string | null;
  result?: Array<GetUsuarioDto> | null;
  success?: boolean;
}
