/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Usuario } from '../models/usuario';
export interface HistoryPass {
  consecutivo?: number;
  fecha?: string;
  hashPassword?: string | null;
  usuario?: Usuario;
  usuarioId?: string | null;
}
