/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ListaAccionDto } from '../models/lista-accion-dto';
export interface ListaAccionDtoListApiResponse {
  message?: string | null;
  result?: Array<ListaAccionDto> | null;
  success?: boolean;
}
