/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ListaAccionDto {
  codAccion?: string | null;
  descripcion?: string | null;
  seccion?: string | null;
}
