/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ListaProveedoresDto } from '../models/lista-proveedores-dto';
export interface ListaProveedoresDtoListApiResponse {
  message?: string | null;
  result?: Array<ListaProveedoresDto> | null;
  success?: boolean;
}
