/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ListaEmpresasDto {
  activa?: boolean;
  empresaId?: string | null;
  fechaCreacion?: string;
  listaPlantas?: Array<string> | null;
  listaProveedores?: Array<string> | null;
  razonSocial?: string | null;
  rfc?: string | null;
  rfcRepresentanteLegal?: string | null;
  versionCtrVol?: string | null;
}
