/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ListaEmpresasDto } from '../models/lista-empresas-dto';
export interface ListaEmpresasDtoApiResponse {
  message?: string | null;
  result?: ListaEmpresasDto;
  success?: boolean;
}
