/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ListaPlantaDto } from '../models/lista-planta-dto';
export interface ListaPlantaDtoListApiResponse {
  message?: string | null;
  result?: Array<ListaPlantaDto> | null;
  success?: boolean;
}
