/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ListaProveedoresDto {
  activo?: boolean | null;
  noProveedor?: string | null;
  numPermiso?: string | null;
  razonSocialP?: string | null;
  rfcP?: string | null;
}
