/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ListaEmpresasDto } from '../models/lista-empresas-dto';
export interface ListaEmpresasDtoListApiResponse {
  message?: string | null;
  result?: Array<ListaEmpresasDto> | null;
  success?: boolean;
}
