/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ListaPerfilesDto {
  descripcion?: string | null;
  listaAcciones?: Array<string> | null;
  listaEmpresas?: Array<string> | null;
  perfil?: string | null;
  perfilId?: number;
}
