/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ListaPerfilesDto } from '../models/lista-perfiles-dto';
export interface ListaPerfilesDtoListApiResponse {
  message?: string | null;
  result?: Array<ListaPerfilesDto> | null;
  success?: boolean;
}
