/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ListaUsuarioPlanta } from '../models/lista-usuario-planta';
export interface ListaUsuarioPlantaListApiResponse {
  message?: string | null;
  result?: Array<ListaUsuarioPlanta> | null;
  success?: boolean;
}
