/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ListaUsuarioPlanta {
  activo?: boolean;
  correo?: string | null;
  listaPlantas?: Array<string> | null;
  nombre?: string | null;
  password?: string | null;
  perfilDescripcion?: string | null;
  perfilId?: number;
  primeraVez?: boolean;
  updatePassword?: string;
  usuarioId?: string | null;
}
