/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Plantum } from '../models/plantum';
import { Tanque } from '../models/tanque';
export interface MedicionTanque {
  claveIdentificacionTanque?: string | null;
  consecutivo?: number;
  incertidumbreMedicionSistMedicionTanque?: number;
  localizOdescripSistMedicionTanque?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  sistemaMedicionTanque?: string | null;
  tanque?: Tanque;
  vigenciaCalibracionSistMedicionTanque?: string;
}
