/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Plantum } from '../models/plantum';
export interface MedicionDispensario {
  claveDispensario?: string | null;
  consecutivo?: number;
  incertidumbreMedicionSistMedicionDispensario?: number;
  localizOdescripSistMedicionDispensario?: string | null;
  planta?: Plantum;
  plantaId?: string | null;
  sistemaMedicionDispensario?: string | null;
  vigenciaCalibracionSistMedicionDispensario?: string;
}
