/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Perfile } from '../models/perfile';
import { Plantum } from '../models/plantum';
export interface PerfilEmpresa {
  empresa?: Empresa;
  empresaId?: string | null;
  perfil?: Perfile;
  perfilId?: number;
  planta?: Plantum;
  plantaId?: string | null;
}
