/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PerfilEmpresaDto } from '../models/perfil-empresa-dto';
export interface PerfilEmpresaDtoListApiResponse {
  message?: string | null;
  result?: Array<PerfilEmpresaDto> | null;
  success?: boolean;
}
