/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Accione } from '../models/accione';
import { PerfilEmpresa } from '../models/perfil-empresa';
import { Usuario } from '../models/usuario';
export interface Perfile {
  acciones?: string | null;
  codAccions?: Array<Accione> | null;
  descripcion?: string | null;
  perfil?: string | null;
  perfilEmpresas?: Array<PerfilEmpresa> | null;
  perfilId?: number;
  usuarios?: Array<Usuario> | null;
}
