/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PerfilAccion } from '../models/perfil-accion';
import { PerfilEmpresa } from '../models/perfil-empresa';
import { Usuario } from '../models/usuario';
export interface Perfile {
  acciones?: string | null;
  descripcion?: string | null;
  perfil?: string | null;
  perfilAccions?: Array<PerfilAccion> | null;
  perfilEmpresas?: Array<PerfilEmpresa> | null;
  perfilId?: number;
  usuarios?: Array<Usuario> | null;
}
