/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PerfilEmpresaDto {
  descripcionEmpresa?: string | null;
  empresaId?: string | null;
  perfilId?: number;
}
