/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Accione } from '../models/accione';
import { Perfile } from '../models/perfile';
export interface PerfilAccion {
  codAccion?: string | null;
  codAccionNavigation?: Accione;
  id?: string | null;
  perfil?: Perfile;
  perfilId?: number;
}
