/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PerfilAccionDto {
  codAccion?: string | null;
  descripcionAccion?: string | null;
  perfilId?: number;
}
