/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PerfilAccionDto } from '../models/perfil-accion-dto';
export interface PerfilAccionDtoListApiResponse {
  message?: string | null;
  result?: Array<PerfilAccionDto> | null;
  success?: boolean;
}
