/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentoProducto } from '../models/documento-producto';
import { EmpresaProducto } from '../models/empresa-producto';
import { GasLp } from '../models/gas-lp';
import { PlantaProducto } from '../models/planta-producto';
export interface Producto {
  activo?: boolean | null;
  concentracionSustanciaMarcaje?: string | null;
  descripcion?: string | null;
  documentoProductos?: Array<DocumentoProducto> | null;
  empresaProductos?: Array<EmpresaProducto> | null;
  gasLp?: GasLp;
  idClaveProducto?: number;
  idClaveSubProducto?: number | null;
  idUm?: number;
  marcaComercial?: string | null;
  marcaje?: string | null;
  plantaProductos?: Array<PlantaProducto> | null;
  productoId?: string | null;
}
