/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmpresaProveedor } from '../models/empresa-proveedor';
export interface Proveedore {
  activo?: boolean | null;
  codigoP?: string | null;
  empresaId?: string | null;
  empresaProveedors?: Array<EmpresaProveedor> | null;
  noProveedor?: string | null;
  numPermiso?: string | null;
  plantaId?: string | null;
  razonSocialP?: string | null;
  rfcP?: string | null;
}
