/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Empresa } from '../models/empresa';
import { Plantum } from '../models/plantum';
export interface RecepcionDiario {
  claveIdentificacionTanque?: string | null;
  empresa?: Empresa;
  empresaId?: string | null;
  fechaYhoraFinalRecepcion?: string | null;
  fechaYhoraInicioRecepcion?: string | null;
  isDucto?: boolean | null;
  noDocumento?: string | null;
  numerDeRegistro?: number;
  planta?: Plantum;
  plantaId?: string | null;
  presionAbsoluta?: number | null;
  temperatura?: number | null;
  volFinalTanqueValorNumerico?: number | null;
  volInicialTanqueValorNumerico?: number | null;
  volRecepValorNumerico?: number | null;
}
