/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompAlmCfdinacional } from '../models/comp-alm-cfdinacional';
import { DocumentoProducto } from '../models/documento-producto';
import { DocumentoTanque } from '../models/documento-tanque';
import { EntregasMensuale } from '../models/entregas-mensuale';
import { RecepcionesMensuale } from '../models/recepciones-mensuale';
import { Tanque } from '../models/tanque';
export interface TClaveUnidadMedidum {
  claveUnidadMedida?: string | null;
  compAlmCfdinacionals?: Array<CompAlmCfdinacional> | null;
  descripcion?: string | null;
  documentoProductos?: Array<DocumentoProducto> | null;
  documentoTanques?: Array<DocumentoTanque> | null;
  entregasMensuales?: Array<EntregasMensuale> | null;
  id?: number;
  recepcionesMensuales?: Array<RecepcionesMensuale> | null;
  tanques?: Array<Tanque> | null;
}
