/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CEstadoTanque } from '../models/c-estado-tanque';
import { MedicionTanque } from '../models/medicion-tanque';
import { Plantum } from '../models/plantum';
import { TClaveUnidadMedidum } from '../models/t-clave-unidad-medidum';
export interface Tanque {
  capFondajeValorNumerico?: number | null;
  capGasTalonValorNumerico?: number | null;
  capOperativaValorNumerico?: number;
  capTotalValorNumerico?: number;
  capUtilValorNumerico?: number;
  claveIdentificacionTanque?: string | null;
  estadoTanque?: string | null;
  estadoTanqueNavigation?: CEstadoTanque;
  localizacionYodescripcionTanque?: string | null;
  medicionTanques?: Array<MedicionTanque> | null;
  planta?: Plantum;
  plantaId?: string | null;
  um?: number;
  umNavigation?: TClaveUnidadMedidum;
  vigenciaCalibracionTanque?: string;
  volMinOperaValorNumrico?: number;
}
