/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CTipoImpExp } from '../models/c-tipo-imp-exp';
import { Documento } from '../models/documento';
export interface TipoDocumento {
  cTipoImpExp?: CTipoImpExp;
  descripcion?: string | null;
  documentos?: Array<Documento> | null;
  tipoDocumento1?: string | null;
}
