/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Plantum } from '../models/plantum';
export interface UsuarioPlantum {
  planta?: Plantum;
  plantaId?: string | null;
  usuarioId?: string | null;
}
