/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HistoryPass } from '../models/history-pass';
import { Perfile } from '../models/perfile';
export interface Usuario {
  activo?: boolean;
  correo?: string | null;
  historyPasses?: Array<HistoryPass> | null;
  nombre?: string | null;
  password?: string | null;
  perfil?: Perfile;
  perfilId?: number;
  primeraVez?: boolean;
  updatePassword?: string;
  usuarioId?: string | null;
}
