/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsuarioDto } from '../models/usuario-dto';
export interface UsuarioDtoListApiResponse {
  message?: string | null;
  result?: Array<UsuarioDto> | null;
  success?: boolean;
}
