/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Documento } from '../models/documento';
import { Empresa } from '../models/empresa';
export interface VersionControlVolumetrico {
  descripcion?: string | null;
  documentos?: Array<Documento> | null;
  empresas?: Array<Empresa> | null;
  versionCtrVol?: string | null;
}
