/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CrearEmpresaDto } from '../../models/crear-empresa-dto';
import { CrearEmpresaDtoApiResponse } from '../../models/crear-empresa-dto-api-response';

export interface CrearEmpresa$Plain$Params {
      body?: CrearEmpresaDto
}

export function crearEmpresa$Plain(http: HttpClient, rootUrl: string, params?: CrearEmpresa$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CrearEmpresaDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, crearEmpresa$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CrearEmpresaDtoApiResponse>;
    })
  );
}

crearEmpresa$Plain.PATH = '/api/Empresa/CrearEmpresa';
