/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListaEmpresasDtoApiResponse } from '../../models/lista-empresas-dto-api-response';

export interface GetEmpresaByEmpresa$Plain$Params {
  empresaId?: string;
}

export function getEmpresaByEmpresa$Plain(http: HttpClient, rootUrl: string, params?: GetEmpresaByEmpresa$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ListaEmpresasDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, getEmpresaByEmpresa$Plain.PATH, 'get');
  if (params) {
    rb.query('empresaId', params.empresaId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListaEmpresasDtoApiResponse>;
    })
  );
}

getEmpresaByEmpresa$Plain.PATH = '/api/Empresa/GetEmpresaByEmpresa';
