/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListaEmpresasDtoListApiResponse } from '../../models/lista-empresas-dto-list-api-response';

export interface GetAllEmpresas$Json$Params {
}

export function getAllEmpresas$Json(http: HttpClient, rootUrl: string, params?: GetAllEmpresas$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ListaEmpresasDtoListApiResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllEmpresas$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListaEmpresasDtoListApiResponse>;
    })
  );
}

getAllEmpresas$Json.PATH = '/api/Empresa/GetAllEmpresas';
