/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmpresaPlantaDtoListApiResponse } from '../../models/empresa-planta-dto-list-api-response';

export interface GetEmpresaPlanta$Plain$Params {
  empresa?: string;
}

export function getEmpresaPlanta$Plain(http: HttpClient, rootUrl: string, params?: GetEmpresaPlanta$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EmpresaPlantaDtoListApiResponse>> {
  const rb = new RequestBuilder(rootUrl, getEmpresaPlanta$Plain.PATH, 'get');
  if (params) {
    rb.query('empresa', params.empresa, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmpresaPlantaDtoListApiResponse>;
    })
  );
}

getEmpresaPlanta$Plain.PATH = '/api/Empresa/GetEmpresaPlanta';
