/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CrearEmpresaPlantaDto } from '../../models/crear-empresa-planta-dto';

export interface GuardaRelacionEmpresaPlanta$Plain$Params {
      body?: Array<CrearEmpresaPlantaDto>
}

export function guardaRelacionEmpresaPlanta$Plain(http: HttpClient, rootUrl: string, params?: GuardaRelacionEmpresaPlanta$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
  const rb = new RequestBuilder(rootUrl, guardaRelacionEmpresaPlanta$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: String((r as HttpResponse<any>).body) === 'true' }) as StrictHttpResponse<boolean>;
    })
  );
}

guardaRelacionEmpresaPlanta$Plain.PATH = '/api/Empresa/GuardaRelacionEmpresaPlanta';
