/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CrearPerfilDto } from '../../models/crear-perfil-dto';
import { CrearPerfilDtoApiResponse } from '../../models/crear-perfil-dto-api-response';

export interface CrearPerfil$Plain$Params {
      body?: CrearPerfilDto
}

export function crearPerfil$Plain(http: HttpClient, rootUrl: string, params?: CrearPerfil$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CrearPerfilDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, crearPerfil$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CrearPerfilDtoApiResponse>;
    })
  );
}

crearPerfil$Plain.PATH = '/api/Perfil/CrearPerfil';
