/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListaAccionDtoListApiResponse } from '../../models/lista-accion-dto-list-api-response';

export interface GetAcciones$Plain$Params {
}

export function getAcciones$Plain(http: HttpClient, rootUrl: string, params?: GetAcciones$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ListaAccionDtoListApiResponse>> {
  const rb = new RequestBuilder(rootUrl, getAcciones$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListaAccionDtoListApiResponse>;
    })
  );
}

getAcciones$Plain.PATH = '/api/Perfil/GetAcciones';
