/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PerfilEmpresaDtoListApiResponse } from '../../models/perfil-empresa-dto-list-api-response';

export interface GetPerfilEmpresas$Json$Params {
  perfilId?: number;
}

export function getPerfilEmpresas$Json(http: HttpClient, rootUrl: string, params?: GetPerfilEmpresas$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PerfilEmpresaDtoListApiResponse>> {
  const rb = new RequestBuilder(rootUrl, getPerfilEmpresas$Json.PATH, 'get');
  if (params) {
    rb.query('perfilId', params.perfilId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PerfilEmpresaDtoListApiResponse>;
    })
  );
}

getPerfilEmpresas$Json.PATH = '/api/Perfil/GetPerfilEmpresas';
