/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PerfilAccionDtoListApiResponse } from '../../models/perfil-accion-dto-list-api-response';

export interface GetPerfilAccionesByPerfil$Plain$Params {
  perfilId?: number;
}

export function getPerfilAccionesByPerfil$Plain(http: HttpClient, rootUrl: string, params?: GetPerfilAccionesByPerfil$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<PerfilAccionDtoListApiResponse>> {
  const rb = new RequestBuilder(rootUrl, getPerfilAccionesByPerfil$Plain.PATH, 'get');
  if (params) {
    rb.query('perfilId', params.perfilId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PerfilAccionDtoListApiResponse>;
    })
  );
}

getPerfilAccionesByPerfil$Plain.PATH = '/api/Perfil/GetPerfilAccionesByPerfil';
