/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CrearPerfilEmpresaDto } from '../../models/crear-perfil-empresa-dto';

export interface GuardaRelacionPerfilEmpresa$Json$Params {
      body?: Array<CrearPerfilEmpresaDto>
}

export function guardaRelacionPerfilEmpresa$Json(http: HttpClient, rootUrl: string, params?: GuardaRelacionPerfilEmpresa$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
  const rb = new RequestBuilder(rootUrl, guardaRelacionPerfilEmpresa$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: String((r as HttpResponse<any>).body) === 'true' }) as StrictHttpResponse<boolean>;
    })
  );
}

guardaRelacionPerfilEmpresa$Json.PATH = '/api/Perfil/GuardaRelacionPerfilEmpresa';
